trigger:
- main

variables:
  buildConfiguration: 'Release'
stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build_Web
        displayName: 'Build Web'
        variables:
          repo: 'eshoponweb/web'
        steps:
          - script: |
              echo $sourceVersion
              commitHash=${sourceVersion:0:7}
              echo $commitHash
              echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Git Hash 7-digit
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(repo)
              dockerfile: 'src/Web/Dockerfile'
              tags: '$(commitHash)'
              buildContext: '.'
          - task: Bash@3
            displayName: Save Docker Image
            inputs:
              targetType: 'inline'
              script: |
                docker save $(repo):$(commitHash) -o $(Build.ArtifactStagingDirectory)/image_$(commitHash).tar
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(repo)'
              publishLocation: 'Container'
  - stage: Deploy
    displayName: 'Deploy to development'
    dependsOn: Build
    jobs:
      - job: Deploy_Web
        displayName: 'Deploy Web'
        # environment: 'development'
        steps:
          - download: current
          - task: Bash@3
            displayName: Save Docker Image
            inputs:
              targetType: 'inline'
              script: |
                docker load -i $(Pipeline.Workspace)/current/image_$(commitHash).tar
                docker tag $(repo):$(commitHash) acr_name/$(repo):latest
          - task: Bash@3
            displayName: 'deploy'
            inputs:
              targetType: 'inline'
              script: |
                echo 'docker push acr_name/$(repo):latest'
                docker images
                      

                