trigger:
- main

variables:
  buildConfiguration: 'Release'
stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build_Web
        displayName: 'Build Web'
        variables:
          repo: 'eshoponweb/web'
        steps:
          - script: |
              echo $sourceVersion
              commitHash=${sourceVersion:0:7}
              echo $commitHash
              echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Git Hash 7-digit
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(repo)
              dockerfile: 'src/Web/Dockerfile'
              tags: '$(commitHash)'
              buildContext: '.'
          - task: Bash@3
            displayName: Save Docker Image
            inputs:
              targetType: 'inline'
              script: |
                docker save $(repo):$(commitHash) -o $(Build.ArtifactStagingDirectory)/image_$(commitHash).tar
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(repo)'
              publishLocation: 'Container'
      - job: Build_API
        displayName: 'Build API'
        variables:
          repo: 'eshoponweb/api'
        steps:
          - script: |
              echo $sourceVersion
              commitHash=${sourceVersion:0:7}
              echo $commitHash
              echo "##vso[task.setvariable variable=commitHash]$commitHash" ## Set variable for using in other tasks.
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Git Hash 7-digit
          - task: Docker@2
            displayName: Build image
            inputs:
              command: build
              repository: $(repo)
              dockerfile: 'src/PublicApi/Dockerfile'
              tags: '$(commitHash)'
              buildContext: '.'
          - task: Bash@3
            displayName: Save Docker Image
            inputs:
              targetType: 'inline'
              script: |
                docker save $(repo):$(commitHash) -o $(Build.ArtifactStagingDirectory)/image_$(commitHash).tar
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(repo)'
              publishLocation: 'Container'